# This is a basic workflow to help you get started with Actions

name: Getting started with Github actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check the reporsitory under GITHUB_WORKSPACE
      - name: Step1 - Log preBiuld disk space
        run: df
      
      - name: Step 2 - Checks-out your repository
        uses: actions/checkout@v3

      - name: Step 3 - What is in the folder
        run: ls -a

      - name: Step 4 - Check version of Github and Java
        run: 
         git --version
         java -version

      - name: Step 5 - Log the postBuild disk space
        run: df
      
      

      

      
